### ISSUE TITLE
Rusts version gets rebuilt every time from scratch including deps

### ISSUE THREAD

**Issue by elshize** [pisa-engine/ciff#11]
I have a feeling this has something to do with `build.rs` script, but I need to investigate.

**Comment by JMMackenzie** [comment]
Hmm this doesn't seem to happen for me. What steps to reproduce?

**Comment by elshize** [comment]
Oh, it's only on the `lints` branch! I better fix that one :D

**Comment by elshize** [comment]
Ok, so it seems to be sadly caused by the presence of `.cargo/config`, so I've moved the config to `main.rs`, and it works fine. I'll hit the rust discord tomorrow and see if it's a bug or what.
